sudo:          false
language:      node_js
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules

deploy:
  provider: s3
  access_key_id: AKIAIGFYOCE7RLZK7MWA
  secret_access_key: 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
  bucket: williamresume
